<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تنسور (Tensor) و متغیر (Variable)
</font>
</h1>


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ساخت تنسور
</font>
</h2>

In [1]:
import tensorflow as tf

X = tf.constant([[1, 2], [3, 4], [5, 6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
اطلاعات تنسور
</font>
</h2>

In [2]:
print(X.shape)
print(X.device)
print(X.dtype)
print(type(X))

(3, 2)
/job:localhost/replica:0/task:0/device:GPU:0
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نمایه‌سازی و برش تنسور
</font>
</h2>

In [3]:
# keep the first two rows, and the first column
X = X[0:2, 0:1]
X

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]], dtype=int32)>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تبدیل تنسور به آرایه‌ی نامپای
</font>
</h2>

In [4]:
# convert to numpy array
array = X.numpy()
array

array([[1],
       [3]], dtype=int32)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ساخت متغیر
</font>
</h2>

In [5]:
V = tf.Variable(X)
V

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[1],
       [3]], dtype=int32)>

In [6]:
bool_variable = tf.Variable([False, False, False, True])
bool_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [7]:
complex_variable = tf.Variable([5 + 4j, 6 + 1j])
complex_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تغییر مقادیر متغیر
</font>
</h2>

In [8]:
Y = tf.constant([[5], [6]])
V.assign(Y)
V

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[5],
       [6]], dtype=int32)>

In [9]:
V.assign_add([[1], [1]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[6],
       [7]], dtype=int32)>

In [10]:
V.assign_sub([[2], [2]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[4],
       [5]], dtype=int32)>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تبدیل یک متغیر به تنسور
</font>
</h2>

In [11]:
tf.convert_to_tensor(V)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[4],
       [5]], dtype=int32)>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نام و مشتق‌پذیری متغیرها
</font>
</h2>

In [12]:
tf.Variable([2.0, 3.0], name="quera")

<tf.Variable 'quera:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [13]:
step_counter = tf.Variable(1, trainable=False)
step_counter

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>